apiVersion: v1
kind: Service
metadata:
  name: pet-portal-web-service
spec:
  selector:
    app: pet-portal-web
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort